name: Health Check

on:
  workflow_call:

jobs:
  lint-type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - run: yarn install
      - run: yarn lint
      - run: yarn typecheck
